apiVersion: apps/v1
kind: Deployment
metadata:
  name: razib-next
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: razib-next
  template:
    metadata:
      labels:
        app: razib-next
    spec:
      containers:
        - name: web
          image: <DOCKERHUB_USERNAME>/razib-next:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
