apiVersion: v1
kind: Service
metadata:
  name: razib-next-nodeport
  namespace: production
spec:
  type: NodePort
  selector:
    app: razib-next
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080
