name: Display hello.txt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  display-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display contents of hello.txt
        run: |
          if [ -f hello.txt ]; then
            echo "Showing contents of hello.txt:"
            cat hello.txt
          else
            echo "hello.txt does not exist in the repository root."
          fi
